---
- hosts: localhost
  become: true
  become_method: sudo
 
  tasks:
    - name: Update packages and upgrade
      apt:
        update_cache: true
        upgrade: dist
        force_apt_get: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - build-essential
          - git
          - golang-go
          - nmap
          - hashcat
          - john
          - hydra
          - sqlmap
          - openvpn
          - smbclient
          - hashid
          - fcrackzip
          - gpg
          - wget
        state: latest
        update_cache: true
    - name: Add docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Change docker socket permissions
      command: bash -c "chmod 666 /var/run/docker.sock"              
    - name: Install gobuster
      command: bash -c "go install github.com/OJ/gobuster/v3@latest"
      ## install tfenv only for root user
    - name: Check if tfenv dir exists
      stat:
        path: "/root/.tfenv"
      register: tfenv_dir
    - name: Report .tfenv dir exists
      debug:
        msg: ".tfenv dir exists, ommiting installation"
    - name: "Install tfenv"
      command: bash -c "git clone https://github.com/tfutils/tfenv.git ~/.tfenv && echo 'export PATH=$PATH:$HOME/.tfenv/bin' >> ~/.bashrc"
      when: not tfenv_dir.stat.exists
    - name: Add Google official GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present      
    - name: Add Kubernetes Repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
        state: present
        filename: kubernetes
        mode: 0600        
    - name: Installing Kubernetes Cluster Packages.
      apt: 
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present